/**
 * 订单状态
 * @type {{BOOK: 预定待支付, ALLOCATED: 已分配车辆, PICK_UP: 已取车, FINISH: 已完成, RETURN: 已还车, CANCELLED: 已取消}}
 */
export const ORDER_STATUS = {
  BOOK: 'BOOK',
  ALLOCATED: 'ALLOCATED',
  PICK_UP: 'PICK_UP',
  RETURN: 'RETURN',
  CANCELLED: 'CANCELLED',
  FINISH: 'FINISH'
}
/**
 * 订单支付状态
 * @type {{CANCELED_UNPAID: 预约未支付,
 * BOOK_UNPAID: 预定待支付,
 * BOOK_PAID:预约已支付,
 * BOOK_NEED_REFUND: 预定待退款,
 * BOOK_REFUNDING: 预约退款中,
 * BOOK_REFUND_FAILED: 预约退款失败
 * BOOK_REFUND: 预约已退款
 * FINISH_NEED_EXTRA: 最终待支付
 * FINISH_UNPAID: 最终待支付
 * FINISH_NEED_REFUND: 最终待退款
 * FINISH_REFUNDING：最终退款中
 * FINISH_REFUND_FAILED：最终退款失败
 * FINISH_PAID：最终已支付
 * FINISH_REFUND：最终已退款
 * }}
 */
export const ORDER_PAYMENT_STATUS = {
  CANCELED_UNPAID: 'CANCELED_UNPAID',
  BOOK_UNPAID: 'BOOK_UNPAID',
  BOOK_PAID: 'BOOK_PAID',
  BOOK_NEED_REFUND: 'BOOK_NEED_REFUND',
  BOOK_REFUNDING: 'BOOK_REFUNDING',
  BOOK_REFUND_FAILED: 'BOOK_REFUND_FAILED',
  BOOK_REFUND: 'BOOK_REFUND',
  FINISH_NEED_EXTRA: 'FINISH_NEED_EXTRA',
  FINISH_UNPAID: 'FINISH_UNPAID',
  FINISH_NEED_REFUND: 'FINISH_NEED_REFUND',
  FINISH_REFUNDING: 'FINISH_REFUNDING',
  FINISH_REFUND_FAILED: 'FINISH_REFUND_FAILED',
  FINISH_PAID: 'FINISH_PAID',
  FINISH_REFUND: 'FINISH_REFUND'
}
